[parity]
chain = "/root/.local/share/io.parity.ethereum/spec.json"
base_path = "/tmp/parity0"
[network]
port = 30302
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8452
[account]
password = ["/root/.local/share/io.parity.ethereum/node.pwds"]
[mining]
reseal_on_txs = "none"
usd_per_tx = "0"
