[parity]
chain = "/root/.local/share/io.parity.ethereum/spec.json"
base_path = "/tmp/parity0"
[network]
port = 30300
[rpc]
interface = "0.0.0.0"
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
[account]
password = ["/root/.local/share/io.parity.ethereum/node.pwds"]
[mining]
reseal_on_txs = "none"
