# parity_docker_compose.yml
# Creates a directory to transfer the docker-compose file to and deploys containers.

    - set_fact: compose_dir=/var/tmp/ansible-docker-service
    - name: establish docker-compose directory
      become: yes
      file: 
        path: "{{ compose_dir }}"
        state: directory

    - name: Upload docker-compose files
      become: yes
      synchronize: 
        src: "{{ item }}"
        dest: "{{ compose_dir }}"
      with_items:
      - parity_compose
        
    - name: use docker-compose to deploy containers
      become: yes
      docker_service:
        project_src: "{{ compose_dir }}/parity_compose"
