  - name: install core software
    become: yes
    apt:
      name: "{{ item }}"
      state: present
      update-cache: yes
    with_items:
      - git
      - jq
      - apt-transport-https
  - name: Create code directory
    become: yes
    file:
      path: /code
      state: directory
      owner: egrasmick
      group: egrasmick
      mode: 0775
  - include: setup_docker.yml
