# common.yml
# All servers will receive this configuration.

  - name: install core software
    become: yes
    apt:
      name: "{{ item }}"
      state: present
      update-cache: yes
    with_items:
      - git
      - jq
      - apt-transport-https
  - name: Create code directory
    become: yes
    file:
      path: /code
      state: directory
      # this user can be whoever you want!
      owner: root
      group: root
      mode: 0775
  - include: setup_docker.yml
