---
  - import_playbook: setup_server.yml
  - name: install & configure docker
    hosts: GCEtest
    become: yes
    tasks:
    - name: Add docker-ce apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stabl
        state: present
    - name: Add docker-ce GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
        id: 0EBFCD88
    - name: Install docker-ce dependencies
      apt: 
        name: "{{ item }}"
        state: present
        update-cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    - name: Install docker-ce
      apt:
        name: docker-ce
    - name: Install docker-compose
      apt:
        name: docker-compose
